### ISSUE TITLE
Compatibility:Is this compatible with Magento 2.4.0 and PHP 7.4?

### ISSUE THREAD

**Issue by live4soccer7** [mageplaza/magento-2-delete-orders#11]
Is this compatible with Magento 2.4.0 and PHP 7.4?

**Comment by Victor-Mageplaza** [comment]
Hi @live4soccer7 

I'm Victor from Mageplaza. I would like to answer your question.
Yes, the module is available for use with Magento 2.4.0.
Specifically changes to match the inventory_reverse have been added to the module.
You can test the module right now

Thank you!

**Comment by live4soccer7** [comment]
> Hi @live4soccer7
> 
> I'm Victor from Mageplaza. I would like to answer your question.
> Yes, the module is available for use with Magento 2.4.0.
> Specifically changes to match the inventory_reverse have been added to the module.
> You can test the module right now
> 
> Thank you!

Are you releasing a new version with this update?

**Comment by Victor-Mageplaza** [comment]
@live4soccer7 

Yes, for now, you can try it out at the following link:
https://github.com/mageplaza/magento-2-delete-orders/tree/develop

Thank you!

**Comment by simonmaass** [comment]
after update to 2.4 we had issue and created a PR for this: https://github.com/mageplaza/magento-2-delete-orders/pull/10

**Comment by Victor-Mageplaza** [comment]
Hi @simonmaass 

Yes, I have merged your PR.
Thank you!

Best Regards
Victor
