### ISSUE TITLE
Class 'Mageplaza\Core\Helper\Validate' not found

### ISSUE THREAD

**Issue by Sandeepges** [mageplaza/magento-2-delete-orders#13]
I have installed mageplaza extension successfully.
But i get error on admin and unable to see configurations

Class 'Mageplaza\Core\Helper\Validate' not found
![image](https://user-images.githubusercontent.com/38943916/101610566-df52a800-3a21-11eb-9cc3-ef908f5703e5.png)

**Comment by Victor-Mageplaza** [comment]
Hi @Sandeepges 

I'm Victor from Mageplaza. I would like to answer your question.
You need to install module Core. Here is the link: https://github.com/mageplaza/module-core
Please try and let me know about the result.
Thank you!

Best Regards,
Victor

**Comment by Sandeepges** [comment]
Do we need setup:static-content:deploy in developer mode?

**Comment by Victor-Mageplaza** [comment]
You can run all commands needed.
Thank you!

**Comment by Sandeepges** [comment]
But the console returns not required in developer mode

**Comment by Victor-Mageplaza** [comment]
Okay, please install module Core and let me know about the result.
About command, you just need to run setup and deploy.
Thank you!

**Comment by Sandeepges** [comment]
I have reinstalled module core 
still i see
![image](https://user-images.githubusercontent.com/38943916/101620556-1fb82300-3a2e-11eb-8dc9-c53b02483750.png)

**Comment by Sandeepges** [comment]
Hello, I have installed mageplaza core again .facing the same error
