### ISSUE TITLE
only removes the orders visible in the grid

### ISSUE THREAD

**Issue by webrod** [mageplaza/magento-2-delete-orders#16]
This module only removes the orders visible in the grid. i.e. 20 by default.  it does not take into account the whole selection

### Preconditions (*)

2.4.2

### Steps to reproduce (*)

1. Go to orders grid
2. Make any filter than return many orders, more than visible in the grid (which by defaut ony displays 20 per page)
3. Click "select all"; magento says "2000 records found (2000 selected)
4. click on "delete"
5. module says "Do you really want to delete this orders? (2000 records)"
6. Click OK

### Expected result (*)

1. It should says "A total of 2000 order(s) has been deleted."
2.

### Actual result (*)

1. A total of 20 order(s) has been deleted.2.

**Comment by LVViet160998** [comment]
Hello, I am Jerry from Mageplaza Support Team. Please let me assist you with this issue.

Magento Core is responsible for taking the records into account. The Delete Order module has no impact on this calculation. Could you please help me recheck other actions to see if the issue persists or not?
I genuinely appreciate your assistance!

**Comment by KZNcode** [comment]
Can confirm this is an issue... Tested with 60,000 orders... Only deletes orders listed on the first page--even if you select all.

**Comment by KhietNguyen83** [comment]
Hi @webrod @KZNcode ,
Please help me to do the following:
- Open the file app/code/Mageplaza/DeleteOrders/view/adminhtml/ui_component/sales_order_grid.xml line 24

Current code:
- <massaction name="listing_massaction">

Replace:
- <massaction name="listing_massaction" component="Magento_Ui/js/grid/tree-massactions">

https://i.imgur.com/X5Rf3fH.png
Thank you!
