### ISSUE TITLE
order shipping info and invoice info not delete

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-delete-orders#2]
on the backend ,delete order,but the shiping info and invoice info not delete
on the sales->shipments and sales-> invoice grid ,also exit the shipping info and invoice info
how to solve the problem?

**Comment by Leaden-Hall** [comment]
Sorry for the late response

The actual related documents (shipments, invoices, credit memos) do get deleted when the original order is deleted. However, on the invoice, shipment and credit memo gird; the record is still present because the data displayed from such a grid is retrieved from a completely separated table.
Magento 2 does not support deleting items from the admin grid so it is quite a trouble to remove it entirely. We are working on it for the next module update.
Please stay tuned

**Comment by DePalmo** [comment]
Any ETA on the update?

**Comment by Leaden-Hall** [comment]
Since Magento 2 doesn't support deleting records from the admin grid directly, we are working on a much more resourceful solution.
We just don't really want to mess around with the Magento 2 core functionalities, so an exact ETA is quite hard to tell at the moment.

**Comment by DePalmo** [comment]
Wasn't expecting an exact ETA, but at least approx. would be better than nothing.

**Comment by Leaden-Hall** [comment]
Sorry for the late response

About 2 weeks, maybe more or less.

**Comment by DePalmo** [comment]
Thank you.

**Comment by magenizr** [comment]
@DePalmo 

We will release a free DeleteOrders module in the next few days, which will delete all related data such as invoice, shipment or credit memo. Here is how you can temporarily fix it.

1. Edit Controller/Adminhtml/Order/MassDelete.php in Mageplaza_DeleteOrders
2. Go to line 91

```
$this->orderRepository->delete($order);
```

3. Replace it with

```
// fix start
$invoices = $order->getInvoiceCollection();

if ($invoices) {

    foreach($invoices as $invoice) {
        $invoice->delete();
    }
}

$shipments = $order->getShipmentsCollection();

if ($shipments)
{
    foreach($order as $shipment) {
        $shipment->delete();
    }
}

$creditmemos = $order->getCreditmemosCollection();

if ($creditmemos) {

    foreach($creditmemos as $creditmemo) {
        $creditmemo->delete();
    }
}
// fix end

$this->orderRepository->delete($order);
```

We hope this will help.

**Comment by DePalmo** [comment]
Thank you for the update and instructions, but will await for the release of updated version and try it then.

**Comment by DePalmo** [comment]
Yesterday I tried the updated extension and I am glad to report that it's working! The only issue at the moment are the records left from before when the extension didn't work properly. The Orders are removed and data for Invoices too, but records for Invoices are still there. Any suggestion on how to remove those as well?

**Comment by DePalmo** [comment]
As said, the update works and now it does remove all data related to order (all invoices, shipments, credit memos, etc.), but the problems are old data, old orders that were deleted previously and invoice records left in the system. Now those invoice records can't be opened nor deleted.

Will contact your team there, thank you for the link.

**Comment by Desmond-MagePlaza** [comment]
Thanks.
Looking forward to your contact.
