### ISSUE TITLE
Error on setup:upgrade when configuration null

### ISSUE THREAD

**Issue by memen45** [mageplaza/magento-2-delete-orders#20]
https://github.com/mageplaza/magento-2-delete-orders/blob/44bc6c2d219a24b66dd4c01d20f32b1f61733360/Model/Config/Backend/Order/Frequency.php#L118

Installed the package using composer and set the settings I needed on develop server. The package is enabled, but Automatic Delete and Email Notifications are deactivated. Now `bin/magento app:config:dump scopes system` is executed and the config.php added to git. When trying to deploy the server using the new config.php results in an error: 
```
Import failed: Notice: Trying to access array offset on value of type null in /var/www/my-shop/releases/28/vendor/mageplaza/module-delete-orders/Model/Config/Backend/Order/Frequency.php on line 118
```
The time attribute in config.php is set to null, so that explains why array indexing gives an error, however, I would not expect it to error when the setting is not used at all. Could this be fixed?

Magento version: 2.4.3
Module version: 4.0.1

**Comment by KhietNguyen83** [comment]
Hi @memen45 ,
We have released a new module version and solved the above problem.

**Comment by memen45** [comment]
Thanks for the update! The latest tag is still 4.0.1, so which version contains the fix and when could it be expected to be published in the package repository?

**Comment by memen45** [comment]
Hi @KhietNguyen83, Do you have any update on this? The latest tag is still 4.0.1, should it be updated or should I manually add another branch to composer to include the fix?
