### ISSUE TITLE
 Fatal error issue

### ISSUE THREAD

**Issue by Sumayah90** [mageplaza/magento-2-delete-orders#3]
Hi Mageplaza Team,

I have faced this issue after I install Delete orders and re-compile 

 Fatal error:  Class 'Mageplaza\Core\Helper\AbstractData' not found in /srv/users/serverpilot/apps/staging-albassamest/public/app/code/Mageplaza/DeleteOrders/Helper/Data.php on line 30

Fatal error: Class 'Mageplaza\Core\Helper\AbstractData' not found in /srv/users/serverpilot/apps/staging-albassamest/public/app/code/Mageplaza/DeleteOrders/Helper/Data.php on line 30

Ho can I fix it?

**Comment by Desmond-MagePlaza** [comment]
Hi Sumayah90,

Did you install MagePlaza Core module?
https://github.com/mageplaza/module-core

**Comment by Sumayah90** [comment]
No 
I will install and check 

Thanks

**Comment by Desmond-MagePlaza** [comment]
You need the Core module to install MagePlaza's extension.
Please download and install it, then everything is set to go.

Thanks

**Comment by Sumayah90** [comment]
@Desmond-Mageplaza 
Its solved 

Thank you

**Comment by simonmaass** [comment]
please close issue
