### ISSUE TITLE
Fatal error while using the plugin

### ISSUE THREAD

**Issue by jgcabanas** [mageplaza/magento-2-delete-orders#4]
Hi, I installed the plugin, but when I want to see the orders I get a fatal error with 'Plugin class Mageplaza\\DeleteOrders\\Plugin\\Order\\AddDeleteAction doesn't exist'...Any clues ?
Best regards,
JG Cabanas

**Comment by bien119** [comment]
Hi Cabanas,
Please update the latest version of DeleteOrders extension and module-core with the link below.

- https://github.com/mageplaza/magento-2-delete-orders

- https://github.com/mageplaza/module-core

The message specifys AddDeleteAction class doesn't exist on module. you can driectly check it (http://prntscr.com/lwrtwm)

**Comment by bien119** [comment]
This issue will be closed (no response in 7 days). Hope you have a good result with my solution.
