### ISSUE TITLE
Class 'Mageplaza\Core\Helper\Validate' not found

### ISSUE THREAD

**Issue by zw1111** [mageplaza/magento-2-delete-orders#6]
After installing the mageplaza/module-delete-orders, I am getting an error message at the top of my admin pages stating "Class 'Mageplaza\Core\Helper\Validate' not found".  I also see no options to configure the extension.

![mageplaza-delete-orders-extension-issue](https://user-images.githubusercontent.com/54848229/66493749-96e9d400-ea84-11e9-8df0-54faa6bf286b.jpg)

Versions installed:
Magento Community 2.3.3
mageplaza/module-core 1.4.6
mageplaza/module-delete-orders 1.2.0

Does this not work with the latest Magento 2.3.3?  How to I resolve this issue?

**Comment by Victor-Mageplaza** [comment]
Hi @zw1111 
I'm Victor from Mageplaza.
Please re-install extension and restarting the apache2 webserver. It's will take effect.
Thank you!

**Comment by zw1111** [comment]
Thanks Victor... I believe the key think here was the restarting of the apache2 web server using "systemctl restart apache2".  I think the cache within apache2 was not clearing completely until that was done.

After the restart, I was able to activate/register and use the delete orders extension both from the Sales > Order page as well as within an Order.  Awesome!  Thanks!

**Comment by jmpedrosa** [comment]
this issue is not fixed on version 1.4.8

**Comment by Sandeepges** [comment]
I have reinstalled and restarted server,but still I see the error

**Comment by charismeki** [comment]
hi there, what was the solution in the end because i am facing the same issue. thx
