### ISSUE TITLE
Product quantities not restored after deleting order

### ISSUE THREAD

**Issue by jakubfindura** [mageplaza/magento-2-delete-orders#7]
Hi,

after deleting an order, the ordered product quantities are not added back to store.
At first I thought it is because of incompatibility with new Magento Inventory Management added with version 2.3. But after trying it with disabled inventory management, the problem is still there.

I'm not sure if your plugin has this functionality or there is a bug or conflict with other third-party plugin. 

Thanks for answer

**Comment by Victor-Mageplaza** [comment]
Hi @jakubfindura 
Yes, it's a fairly obvious bug starting to appear in version 2.3.
We have been finalizing the update of the module.
Because the changes to suit 2.3 are quite a lot. If you want to fix it immediately, please contact us via ticket at the online support portal.
Thank you!
