### ISSUE TITLE
Can not delete all orders

### ISSUE THREAD

**Issue by fischr20** [mageplaza/magento-2-delete-orders#9]
Hi Mageplaza Team,

the delete button is missing on order grid after installing and enabling the plugin.
Magento ver. 2.3.3

Could you please help?

Many Thanks

**Comment by Victor-Mageplaza** [comment]
Hi @fischr20,
I'm Victor from Mageplaza. I would like to answer your question.

You should try deploying again.
Also, is the delete button still on the order details page?

Thank you!

**Comment by fischr20** [comment]
Hi Victor,

thanks for your answer.

Yes, i‘ve deployed for several times.

The delete button is still on the order detail page.

Many thanks


Am 09.04.2020 um 03:29 schrieb Victor-Mageplaza <notifications@github.com>:

﻿

Hi @fischr20<https://github.com/fischr20>,
I'm Victor from Mageplaza. I would like to answer your question.

You should try deploying again.
Also, is the delete button still on the order details page?

Thank you!
